### PR TITLE
2 segments additions

### PR DESCRIPTION
**Pull request by neturmel**
presets for 2 LED segments

setup:
  seg0: 8 LEDs (nozzle ring)
  seg0: 144 LEDs (should also work for less LEDs)

also made presets for error and waitung and a file with gcode macros for the presets 
(so I don't have to lookup what preset 13 is)

### CODE REVIEW

**Comment by iamlite** [comment]
Hello. I just pushed some local changes. It seems we had a similar idea. Can you submit the config for dual segments separately? I'm not sure how to partially approve a PR, but we would have conflicts otherwise.

**Comment by iamlite** [comment]
Unfortunately, it looks like we both added presets with conflicting numbers. 
I do appreciate your contribution, though!

**Comment by neturmel** [comment]
Hallo Lite,

no problem, you could use it or not, just thought I could share my presets. 
The Liteburner itself is just what I was waiting for.
 
Thanks!
 
 
 

Am Montag, 8. April 2024 um  16:10 wurde geschrieben:

**Comment by neturmel** [comment]
Hallo iamlite/liteburner,

I am really not that good with github, but I will try another approach.

Am Montag, 8. April 2024 um  17:20 wurde geschrieben:

> Hallo Lite,

> no problem, you could use it or not, just thought I could share my presets. 
> The Liteburner itself is just what I was waiting for.
>  
> Thanks!
>  
>  
>  

> Am Montag, 8. April 2024 um  16:10 wurde geschrieben:

>> Unfortunately, it looks like we both added presets with conflicting numbers.
>> I do appreciate your contribution, though!
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you authored the thread.

-- 
Mit freundlichen Grüßen,
Juergen Scherer

**Comment by neturmel** [comment]
{ "0": {}, "4": { "on": true, "bri": 100, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 8, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 74, "sx": 255, "ix": 255, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 152, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 74, "sx": 128, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "led_printing", "ql": "4" }, "1": { "on": true, "bri": 70, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 8, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 37, "sx": 183, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 1 }, { "id": 1, "start": 8, "stop": 152, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 37, "sx": 128, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "led_idle", "ql": "1" }, "6": { "on": true, "bri": 52, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 1, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 199, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 26, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 128, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "printing_1" }, "2": { "on": true, "bri": 60, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 8, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 29, "sx": 128, "ix": 128, "pal": 50, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 152, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 29, "sx": 128, "ix": 128, "pal": 50, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }, { "stop": 0 }], "n": "led_print_start", "ql": "2" }, "3": { "on": true, "bri": 70, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 8, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 97, "sx": 255, "ix": 255, "pal": 8, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 2 }, { "id": 1, "start": 8, "stop": 152, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 97, "sx": 128, "ix": 128, "pal": 8, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "led_heating", "ql": "3" }, "7": { "on": true, "bri": 52, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 2, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 199, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 44, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 128, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "printing_2" }, "8": { "on": true, "bri": 52, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 3, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 199, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 62, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 128, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "printing_3" }, "9": { "on": true, "bri": 52, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 3, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 199, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 62, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 128, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "printing_4" }, "10": { "on": true, "bri": 52, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 5, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 199, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 98, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 128, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "printing_5" }, "5": { "on": true, "bri": 116, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 8, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 111, "sx": 255, "ix": 56, "pal": 10, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 152, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 111, "sx": 128, "ix": 128, "pal": 10, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "led_print_end", "ql": "5" }, "11": { "on": true, "bri": 52, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 6, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 199, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 116, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 128, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "printing_6" }, "14": { "on": true, "bri": 70, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 8, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 27, "sx": 128, "ix": 128, "pal": 0, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 1 }, { "id": 1, "start": 0, "stop": 152, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 27, "sx": 128, "ix": 128, "pal": 0, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 1 }], "n": "led_waiting" }, "12": { "on": true, "bri": 52, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 7, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 199, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 134, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 128, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "printing_7" }, "15": { "on": true, "bri": 133, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 8, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 24, "sx": 221, "ix": 128, "pal": 0, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 152, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 24, "sx": 221, "ix": 128, "pal": 0, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "led_error" }, "13": { "on": true, "bri": 52, "transition": 7, "mainseg": 0, "seg": [{ "id": 0, "start": 0, "stop": 8, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 199, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }, { "id": 1, "start": 8, "stop": 152, "grp": 1, "spc": 0, "of": 0, "on": true, "frz": false, "bri": 255, "cct": 127, "set": 0, "n": "", "col": [
                [255, 170, 0],
                [0, 0, 0],
                [0, 0, 0]
            ], "fx": 2, "sx": 128, "ix": 128, "pal": 28, "c1": 128, "c2": 128, "c3": 16, "sel": true, "rev": false, "mi": false, "o1": false, "o2": false, "o3": false, "si": 0, "m12": 0 }], "n": "printing_8" } }

**Pull request closed without merging**
